# Generated by Django 2.2.5 on 2020-01-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200102_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='books',
            name='image_url',
            field=models.ImageField(upload_to='img'),
        ),
    ]
