# Generated by Django 2.2.5 on 2020-01-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200103_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='books',
            name='qr_book_url',
        ),
        migrations.AddField(
            model_name='books',
            name='qr_book',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
    ]
