# Generated by Django 2.2.5 on 2020-01-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200122_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(default=0, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='downloaded',
            field=models.IntegerField(default=0, verbose_name='количество закачек'),
        ),
    ]
