# Generated by Django 2.2.5 on 2020-01-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200130_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='description',
            new_name='book_desc',
        ),
    ]
