# Generated by Django 2.2.5 on 2020-01-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200130_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_desc',
        ),
    ]
