# Generated by Django 2.2.5 on 2020-01-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_books_book_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_desc',
            field=models.TextField(default=' ', verbose_name='описание'),
        ),
    ]
