# Generated by Django 2.2.5 on 2020-02-04 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_books_book_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestsellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestseller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Books')),
            ],
            options={
                'verbose_name': 'Книгу',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
