# Generated by Django 2.2.5 on 2020-02-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_bestsellers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestsellers',
            options={'verbose_name': 'Бестселлер', 'verbose_name_plural': 'Бестселлеры'},
        ),
    ]
