# Generated by Django 2.2.5 on 2020-02-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200204_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bestseller',
            field=models.BooleanField(default=False, verbose_name='бестселлер'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bestsellers',
        ),
    ]
