# Generated by Django 2.2.5 on 2020-02-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200205_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='total_downloads',
            field=models.IntegerField(default=0, verbose_name='общая закачка'),
        ),
    ]
