# Generated by Django 2.2.5 on 2020-02-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_books_total_downloads'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalDownloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_downloads', models.IntegerField(default=0, verbose_name='общая закачка')),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='total_downloads',
        ),
    ]
